### ISSUE TITLE
defaults are confusing

### ISSUE THREAD

**Issue by evilsneer** [oliyh/martian#108]
Hi!

I have a schema 

```
{:data 
  {#schema.core.OptionalKey{:k :name} 
   #schema.core.Maybe{:schema #schema.core.Predicate{:p? #object[cljs$core$string_QMARK_], :pred-name string?}},     

  #schema.core.OptionalKey{:k :description} #schema.core.Maybe{:schema #schema.core.Predicate{:p?   #object[cljs$core$string_QMARK_], :pred-name string?}}, 

  :goal #schema.core.Predicate{:p? #object[cljs$core$integer_QMARK_], :pred-name integer?}, 

 :dataset #schema.core.Predicate{:p? #object[cljs$core$string_QMARK_], :pred-name string?}, 

 #schema.core.OptionalKey{:k :state} #schema.core.Maybe{:schema #martian.schema.SchemaWithMeta{:schema #schema.core.EnumSchema{:vs #{1 2}}, :meta {:default 2}}}, 

  #schema.core.OptionalKey{:k :systems} [#schema.core.Predicate{:p? #object[cljs$core$integer_QMARK_], :pred-name integer?}], 

  #schema.core.OptionalKey{:k :type} #schema.core.Maybe{:schema #schema.core.Predicate{:p? #object[cljs$core$integer_QMARK_], :pred-name integer?}}, 

 #schema.core.OptionalKey{:k :pk} #schema.core.Maybe{:schema #schema.core.Predicate{:p? #object[cljs$core$integer_QMARK_], :pred-name integer?}}}}
```

as you see, `:state` key has defaults

I'd added `merge-defaults` in :interceptors, and it merge defaults. 
but:

1.  ignores `:schema` key value
2.  If I don't want to use `merge-defaults`, schema still has `:schema` and `:meta` keys, and it is not very handy (because I assume without `merge-defaults` it waits for `:state` key has atomic value);

```
{:data {:systems [586], :goal 1,
:type 1, :dataset "586", :data
{:state {:schema 1}}, :name "two"}}
```
(as schema defines)

but actual data sended as request is 

without `merge-defaults`
```
{"name":"two","goal":1,"dataset":"586","systems":[586],"type":1}
```
so it does not has no `state` key at all.

with `merge-defaults`
```
{"name":"two","goal":1,"dataset":"586","systems":[586],"type":1, "state":2}
```
so it has wrong (= default, but != value from data) value for `state` key

May be it is better to let schema be as it was before defaults (0.1.16), keeping defaults meta info somewhere else?

**Comment by oliyh** [comment]
Hi,

In `0.1.17-SNAPSHOT` I have re-written how the defaults work, it now uses `metosin/schema-tools` which should be a bit more predictable - could you let me know how you get on?

Thanks

**Comment by evilsneer** [comment]
hi! 
I use `bootstrap-openapi` with `:use-defaults?  true` in opts, and when I call martian method with 
```
{:data {:name "1", :dataset "586",
:goal 1, :systems [586]}}
```

then actual data, sent in request, is 
```
{"name":"1","goal":1,"dataset":"586","systems":[586]}
```

but, I assume, it should has `state` as well, shouldn't it?

In other aspects it become much useful, thanks!

**Comment by oliyh** [comment]
Hi,

I think it must be because it's an optional key, which suggests it won't add it if they key is not present. If you set `:state nil` I think it would set the value (this behaviour now comes from schema-tools which is why I'm not sure).

**Comment by evilsneer** [comment]
mm, I see. okey!👍
