### ISSUE TITLE
malli support

### ISSUE THREAD

**Issue by xificurC** [oliyh/martian#114]
I see the core library depends on schema and spec. The examples in the readme all use schema when bootstrapping. Could malli be used instead?

**Comment by oliyh** [comment]
Hello,

The internal structures used for validation and coercion of requests are schema. Spec is used for documentation and validation of Martian's internal structure, although I have an incomplete branch using spec for request validation as well.

Malli could also be a possibility here too. I guess if it can be sufficiently abstracted from implementation then any library could be plugged in. It would probably be a lot of work though and I don't have any intention to do this in the near future.

**Comment by xificurC** [comment]
Thanks, it's not exactly a burning issue right now.
