### ISSUE TITLE
Use clj-commons/clj-http-lite?

### ISSUE THREAD

**Issue by vemv** [oliyh/martian#170]
Hey there,

https://github.com/clj-commons/clj-http-lite is the latest-and-greatest iterarion of the clj-http-lite fork saga.

It would seem great if that one was used.

Cheers - V

**Comment by oliyh** [comment]
Hi @vemv ,
Thanks for bringing this to my attention, will try it out soon.

Cheers

**Comment by oliyh** [comment]
Closed in #172

**Comment by oliyh** [comment]
Fixed, thanks!
