### ISSUE TITLE
No matching content-type available for `application-json`

### ISSUE THREAD

**Issue by LucianoLaratelli** [oliyh/martian#184]
Hello,

I'm trying out Martian for the [YNAB API](https://api.ynab.com/v1):
```clj
(ns user
  (:require [martian.clj-http :as martian-http]
            [martian.core :as martian]))

(def add-authentication-header
  {:name ::add-authentication-header
   :enter (fn [ctx]
            (assoc-in ctx [:request :headers "Authorization"] "Authorization: Bearer my-cool-bearer-token"))})

(def m (martian-http/bootstrap-openapi
        "https://api.ynab.com/papi/open_api_spec.yaml"
        {:interceptors (concat martian/default-interceptors
                               [add-authentication-header])}))
```
But I'm getting this message:
```clj
user> (martian/response-for m :get-budgets)
No matching content-type available {:supported-content-types #{}, :available-content-types (application/json), :header Content-Type}
No matching content-type available {:supported-content-types #{}, :available-content-types (application/json), :header Content-Type}
No matching content-type available {:supported-content-types #{}, :available-content-types (application/json), :header Content-Type}
;; => nil
```

What am I doing wrong here? I tried setting content-type manually with an interceptor:
```clj
(def add-json-header
  {:name ::add-json-header
   :enter (fn [ctx]
            (assoc-in ctx [:request :headers "Content-Type"] "application/json"))})
```
But got the same result.

**Comment by oliyh** [comment]
Hello,

There are a couple of things to be aware of here:
1. `martian.core/default-interceptors` does not contain the content encoding/decoding interceptors, or the `perform-request` interceptor you need for a functioning martian. You need to use `martian.clj-http/default-interceptors` in this instance.
2. If your interceptor modifies the request, it needs to go _before_ the `perform-request` interceptor (which is at the end of the default interceptors).

Hopefully then, this code will work:
```clj
(ns user
  (:require [martian.clj-http :as martian-http]
            [martian.core :as martian]))

(def add-authentication-header
  {:name ::add-authentication-header
   :enter (fn [ctx]
            (assoc-in ctx [:request :headers "Authorization"] "Authorization: Bearer my-cool-bearer-token"))})

(def m (martian-http/bootstrap-openapi
        "https://api.ynab.com/papi/open_api_spec.yaml"
        {:interceptors (concat [add-authentication-header]
                               martian-http/default-interceptors)}))
```

**Comment by mmeroberts** [comment]
I am also seeing the 
`No matching content-type available {:supported-content-types #{}, :available-content-types (application/json), :header Content-Type}
`
with the following call:
```
(def m (martian-http/bootstrap-openapi "resources/descriptors.yaml"
                                       {:interceptors
                                        (concat [add-authentication-header
                                                 allow-insecure] 
                                                martian/default-interceptors)}))
```

Is there some extra encoding that I need to add?

**Comment by oliyh** [comment]
Hi @mmeroberts ,

As above, you need to change `martian/default-interceptors` to `martian-http/default-interceptors` as only the latter contains the encoding/decoding and `perform-request` interceptors that you need.

Cheers

**Comment by mmeroberts** [comment]
@oliyh my code is as follows:
```
(def m (martian-http/bootstrap-openapi "resources/example.yaml"
                                       {:interceptors
                                        (concat [add-authentication-header
                                                 allow-insecure] 
                                                martian-http/default-interceptors)}))
```
I still get some of the errors about content-type.  This makes me wonder if there should be an extra api call to allow you to see where Martian might have issues with your swagger doc.  This has the feel of either a bug in the swagger or an unsupported option - I might be wrong,

**Comment by mmeroberts** [comment]
> Hi @mmeroberts ,
> 
> As above, you need to change `martian/default-interceptors` to `martian-http/default-interceptors` as only the latter contains the encoding/decoding and `perform-request` interceptors that you need.
> 
> Cheers

My issue was fixed when I added a specific encoder for application/yaml

Thanks

**Comment by oliyh** [comment]
Hi @mmeroberts thanks for the update. Interesting idea about another function on the API to identify potential issues. Martian already has spec instrumentation to help when specifying your own API without swagger, perhaps that could also be leveraged to discover where there are no acceptable content types?

@LucianoLaratelli is your issue also resolved now (thanks for the update to the readme, I think it is clearer now)?
