### ISSUE TITLE
Question: Request Body not contained in bootstrap result (Unlikely bug, likely user-error or OpenAPI spec error)

### ISSUE THREAD

**Issue by dcj** [oliyh/martian#209]
After `bootstrap-openapi` when I `explore` the result, I get: 
```
(pprint (martian/explore c))
No matching content-type available  
{:supported-content-types. 
  #{application/json application/transit+msgpack application/transit+json application/edn}, 
  :available-content-types (application/x-www-form-urlencoded), 
  :header Accept}
```
Followed by a vector-of-vectors specifing the API.

One of the endpoints defined by the API is used to obtain an auth token `POST /auth/token` and a `application/x-www-form-urlencoded` requestBody is required.

When I `(martian/explore c :fetch-token)` the result doesn't contain any information about the request body, 
```
(pprint (martian/explore c :fetch-token))
{:summary "fetch a token",
 :parameters {},
 :returns ...
```
but that is clearly contained within the OpenAPI spec for this endpoint:
```
  /auth/token:
    post:
      tags:
        - Auth
      summary: fetch a token
      operationId: fetchToken
      description: Return an access token based on clientID and clientSecret.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/clientCredentialRequest'
              
     clientCredentialRequest:
      type: object
      description: |
        Body of POST request to /auth/token. Note snake case per https://www.rfc-editor.org/rfc/rfc6749
      required:
        - grant_type
        - client_id
        - client_secret
      properties:
        grant_type:
          type: string
          description: OAuth2 grant type, must be 'client_credentials'
          example: client_credentials
          enum: [client_credentials]
        client_id:
          type: string
          minLength: 1
          maxLength: 4096
          description: client ID to exchange for bearer token.
          example: ven_client_99
        client_secret:
          type: string
          minLength: 1
          maxLength: 4096
          description: client secret to exchange for bearer token.
          example: ven_secret_99
        scope:
          type: string
          minLength: 0
          maxLength: 4096
          description: application defined scope.
          example: read_all
```
Questions:

- Am I just doing this incorrectly?
- Or is the OpenAPI YAML incorrectly specifying the requestBody?
- Or is this something that martian just doesn't deal with?

**Comment by oliyh** [comment]
Hi,

My suspicion is that martian, knowing it doesn't properly support the form content type, is not traversing down into the specification of the body. However I think it could, because it can still parse the spec at bootstrap time even if at runtime it may think it's unable to encode the body.

On the other hand, I haven't really considered what will happen if there are two different specs for two different content types. Martian might have to hold on to both, and choose between them at runtime, but then you would get an ambiguous answer to the `explore` fn because it would depend on which content type you used.

**Comment by oliyh** [comment]
That ref will be resolved by this code: https://github.com/oliyh/martian/blob/master/core/src/martian/openapi.cljc#L146

However Martian is still not looking inside the form-urlencoded bit because it doesn't have an encoder / decoder for that. It should not be too difficult to add one, however, it's fairly basic...

**Comment by dcj** [comment]
Wasn't able to think about this for a few days, back now.
Wondering if code from `ring-codec/src/ring/util/codec.clj` might be useful here?

- https://github.com/ring-clojure/ring-codec/blob/87a58ae46aae329c255b967580ab9c3240b2e2e5/src/ring/util/codec.clj#L114
- https://github.com/ring-clojure/ring-codec/blob/87a58ae46aae329c255b967580ab9c3240b2e2e5/src/ring/util/codec.clj#L133

**Comment by dcj** [comment]
> However Martian is still not looking inside the form-urlencoded bit because it doesn't have an encoder / decoder for that. It should not be too difficult to add one, however, it's fairly basic...

**Comment by oliyh** [comment]
Hi,

Your solution looks good, I expect that to work.
I'll see if I can find time to have a look.

Cheers

**Comment by dcj** [comment]
@oliyh 

> I'll see if I can find time to have a look.

Later tonight I will try to push my code-in-progress up somewhere so that you could just clone it and fire up a REPL, to save you time.  My code small and not proprietary/secret, so no big deal for me.  Also, there is not enough there to get you (or anyone) excited :-)

**Comment by oliyh** [comment]
Hi,

Have a look at the branch `form-encoder`, and the two commits above - I believe this should work?

Cheers

**Comment by dcj** [comment]
@oliyh AFAICT this is working **GREAT!!!**
**Thank you!!!**
Here is what I see now:
```
(pprint (martian/explore ven :fetch-token))

{:summary "fetch a token",
 :parameters
 {:body
  {{:k :scope} java.lang.String,
   :grant-type (enum "client_credentials"),
   :client-id java.lang.String,
   :client-secret java.lang.String}},
  ...
```
I apologize for the delay in testing the branch you created to address this (for me!), I did try right away, but ran into a world of hurt due to bit-rot of my `lein` setup (which I haven't used in several years....), and it took some time to figure out how to extricate myself from that mess....

**Comment by oliyh** [comment]
Hi,

Thanks for the feedback! I will merge this and tag a release.

Cheers

**Comment by oliyh** [comment]
That is what I did :)
