### ISSUE TITLE
Missing dependency for ring-codec

### ISSUE THREAD

**Issue by dcj** [oliyh/martian#212]
When @oliyh awesomely added support for www-url-encoded parameters, the new dependency on `ring-codec` didn't get added to `project.clj`
Shortly I'll push a PR adding that dependency

**Comment by dcj** [comment]
Oops, AFAICT there is no such problem, my mistake.

**Comment by oliyh** [comment]
I added it but need to do a new release, been having problems though. Will do soon

**Comment by oliyh** [comment]
Latest code now released with this fixed
