### ISSUE TITLE
Let user extend deserialiser

### ISSUE THREAD

**Issue by oliyh** [oliyh/martian#23]
E.g. Content-Type XML can't be handled and there is no way for the user to extend it

**Comment by markaddleman** [comment]
Also, please include the serializer.  I am working with an API which requires x-www-form-urlencoded data.  Currently, I believe the best approach to extending martian is to invest a new method and include a new interceptor which detects the new method and performs the appropriate transformation on the request data.

**Comment by oliyh** [comment]
This was implemented in `0.1.8`
