### ISSUE TITLE
It doesn't work (for a lack of a better description)

### ISSUE THREAD

**Issue by saevarb** [oliyh/martian#42]
Hi. I've tried using this library on a json spec which is generated by a library called `servant-swagger`.

This is the spec:

```json
{"swagger":"2.0","info":{"version":"","title":"EZroute api specification"},"host":"localhost:8080","paths":{"/position/update/{id}":{"post":{"consumes":["application/json"],"produces":["application/json"],"parameters":[{"maximum":9223372036854775807,"format":"int64","minimum":-9223372036854775808,"required":true,"in":"path","name":"id","type":"integer"},{"required":true,"schema":{"$ref":"#/definitions/PositionUpdate"},"in":"body","name":"body"}],"responses":{"404":{"description":"`id` not found"},"400":{"description":"Invalid `body`"},"204":{"description":""}}}},"/company":{"get":{"produces":["application/json"],"responses":{"200":{"schema":{"items":{"$ref":"#/definitions/Company"},"type":"array"},"description":""}}}},"/driver":{"get":{"produces":["application/json"],"responses":{"200":{"schema":{"items":{"$ref":"#/definitions/Driver"},"type":"array"},"description":""}}}}},"definitions":{"PositionUpdate":{"required":["position","timestamp"],"properties":{"position":{"$ref":"#/definitions/Coordinate"},"timestamp":{"$ref":"#/definitions/UTCTime"}},"type":"object"},"Coordinate":{"required":["lat","lng"],"properties":{"lat":{"format":"double","type":"number"},"lng":{"format":"double","type":"number"}},"type":"object"},"UTCTime":{"example":"2016-07-22T00:00:00Z","format":"yyyy-mm-ddThh:MM:ssZ","type":"string"},"Company":{"required":["companyName"],"properties":{"companyName":{"type":"string"}},"type":"object"},"Driver":{"required":["driverName","driverLocation","driverCompany"],"properties":{"driverName":{"type":"string"},"driverLocation":{"$ref":"#/definitions/Coordinate"},"driverActive":{"$ref":"#/definitions/Key"},"driverCompany":{"$ref":"#/definitions/Key"}},"type":"object"},"Key":{"required":["unDeviceKey"],"properties":{"unDeviceKey":{"$ref":"#/definitions/BackendKey"}},"type":"object"},"BackendKey":{"required":["unSqlBackendKey"],"properties":{"unSqlBackendKey":{"maximum":9223372036854775807,"format":"int64","minimum":-9223372036854775808,"type":"integer"}},"type":"object"}}}

```

There is no exception if I just use `martin-http/bootstrap-swagger`. I just get an empty vector. Also, I tried it on the pedestal API example, which also didn't work. I have tried unsuccessfully to debug this in the debugger, but I'm pretty new to CLJS and honestly didn't really uncover much. I also tried looking at the source and (mostly) replicating what the http module was doing(it seemed I could just pass it the JSON spec and an URL), and that didn't work either(A vector was indexed with something that wasn't an integer). The stack trace was pretty useless since it doesn't seem to include any of the functions in this library, so I have no idea what is going on.

One last thing: I confirmed that a network request for the swagger spec was being performed successfully. Maybe an exception is being swallowed somewhere? 

Here is the code

```
  (go (let [api (<! (m-http/bootstrap-swagger "http://localhost:3449/spec.json")) ]
        (info api)
        (info (m/explore api))
        ))
```

**Comment by oliyh** [comment]
Hi @saevarb,

At a quick guess, there are no `operationId` keys in the json so they all get filtered out (there isn't really a way of addressing something without an operationId).

**Comment by saevarb** [comment]
Hi. That was indeed the issue. Thank you! Maybe it wouldn't be a bad idea to add thsi as a caveat to the documentation? I can see in the swagger spec that clients *may* use the operationID as unique identifiers, but not everyone reads the swagger spec(and the tools they are using may not mention this).

**Comment by oliyh** [comment]
It is mentioned at the bottom of the readme under 'caveats' but it is a long way down and you won't see it if you're trying to do hello world.

I thought about printing endpoints that were filtered out but libraries shouldn't really do any printing. Perhaps the Martian record could contain a key for warnings. What do you think?

**Comment by davidperrenoud** [comment]
This also confused me. @oliyh Could you generate keywords for paths missing the `operationId` attribute?

For example:
```clojure
[[:missing-operationId-1 "Get all pets in the store"]
 [:missing-operationId-2 "Create a pet"]
 [:missing-operationId-3 "Get a pet by id"]]
```

**Comment by oliyh** [comment]
Hi @davidperrenoud,

I think allowing them through would encourage their use, but it would be very brittle - any endpoint added, removed or renamed could shift the whole list.

Perhaps Martian could accept a callback allowing you to name endpoints given their swagger description, if you do not have control of the API?

**Comment by davidperrenoud** [comment]
No, my idea was not about adding more configuration options but about making the default less confusing. If no `operationId` is available the result looks empty: `[]`

So my idea was that in order to educate the user the keywords could be automatically generated with some inconvenient name, therefore not discouraging their use.

To make the numbering less brittle, a hash function such as `(hash (str path method))` could be used:

```clojure
[[:missing-operationId-920507392 "Get all pets in the store"]
 [:missing-operationId-1090793410 "Create a pet"]
 [:missing-operationId--1717683316 "Get a pet by id"]]
```

Note that simply taking `(keyword (str path method))` would not work for paths containing special characters.
