### ISSUE TITLE
Can't use idiomatic parameters in nested body keys

### ISSUE THREAD

**Issue by OscarMarshall** [oliyh/martian#46]
I'm using Martian to interact with the [Plaid API](https://plaid.com/docs/api/) and a common thing they do is allow a json object to be passed in the post body under the "options" key. For example, the [Balance endpoint](https://plaid.com/docs/api/#balance) allows "account_ids" in the "options" object.

With the config:

```clojure
{:route-name  :get-balance
 :produces    ["application/json"]
 :consumes    ["application/json"]
 :path-parts  ["/institutions/get_by_id"]
 :method      :post
 :body-schema {:get-balance {:access_token
                             schema/Str

                             (schema/optional-key :options)
                             {(schema/optional-key :account_ids) [schema/Str]}}}
 :interceptors [set-client-id-and-secret]}
```

and the parameters `{:access-token "some-access-token", :options {:account-ids ["some-account-id"]}}`, an exception with the message: "clojure.lang.ExceptionInfo: Value cannot be coerced to match schema: {:options {:account-ids disallowed-key}}" is thrown.

Reading through the code, I get the feeling that this use-case wasn't considered. For now I'll just use the snake_cased form for my nested keyword, but I really love the idiomatic parameters feature and would love to see it expanded to work with nested keys.

By the way, this library is genius; I'd always wished for something like this but never was able to put my finger on exactly how to do it. Thank you.

**Comment by oliyh** [comment]
Hi @OscarMarshall, I'm really glad you're enjoying using it! Thanks for submitting this issue.

I think you're right that it doesn't currently support aliasing of deeply nested parameters - some of the functions do but I guess not all of them. It sounds like a reasonable use case though, so I'll have a go at supporting this - hopefully I'll find time in the next few days.

Oliy

**Comment by oliyh** [comment]
Hi @OscarMarshall could you try 0.1.6-SNAPSHOT of the core library and let me know if it solves your use case?

Thanks,
Oliver

**Comment by OscarMarshall** [comment]
Perfect! Works for my use case. Thanks for your quick response @oliyh!
