### ISSUE TITLE
Document the behavior or per-route interceptor chain

### ISSUE THREAD

**Issue by markaddleman** [oliyh/martian#49]
I couldn't find an example of the per-route behavior and the current documentation is unclear how the per-route interceptor chain composes with the global interceptor chain.  Does it replace the global chain?  Is it prepended/appended to the global chain?

**Comment by oliyh** [comment]
Yes, a fair point. They are scheduled within the global chain to sit after the initial request marshalling, but before the serialisation. I will find an appropriate place in the documentation to note this, thank you.

**Comment by markaddleman** [comment]
Thanks!
