### ISSUE TITLE
Question about use of :pet in example

### ISSUE THREAD

**Issue by nisley** [oliyh/martian#50]
In the example below a :pet structure is setup but then :pet is not used.  Is this just a typo?

(let [m (martian/bootstrap "https://api.org"
                           [{:route-name  :create-pet
                             :path-parts  ["/pets/"]
                             :method      :post
                             :body-schema {:pet {:PetId     s/Int
                                                 :FirstName s/Str
                                                 :LastName  s/Str}}}])]

  (martian/request-for m :create-pet {:pet-id 1 :first-name "Doggy" :last-name "McDogFace"}))

**Comment by oliyh** [comment]
Hi @nisley

The body is a special case that can be referred to in one of three ways - via alias `:pet`, via destructuring `:pet-id :first-hand :last-name` or via raw key `:martian.core/body`.

They are equivalent - you can see the test for it here https://github.com/oliyh/martian/blob/master/core/test/martian/core_test.cljc#L233

```clojure
;; these three forms are equivalent, demonstrating destructuring options
(request-for :create-pet {:id 123 :name "charlie"})
(request-for :create-pet {:pet {:id 123 :name "charlie"}})
(request-for :create-pet {::martian/body {:id 123 :name "charlie"}})
```
Hope this makes sense. I will look into improving the documentation on this.

Oliy
