### ISSUE TITLE
Support OpenAPI v3

### ISSUE THREAD

**Issue by troglotit** [oliyh/martian#51]
Hey! Nice stuff!
Unfortunately, my project uses OpenAPI v3, and YAML, it would be dope if martian supported that.

**Comment by oliyh** [comment]
Hi @troglotit 
Sorry it's taken me so long to reply. I agree it would be good to support the latest version, I will try to find time to support it.

In the meantime, PRs are welcome!

**Comment by RafaeLeal** [comment]
Hi
I'd like to work on that, but I think it will require some refactoring..
I was thinking to try to decouple the handler-generation from the swagger/openapi, so I'd probably add an internal data structure that would represent routes. Does that make sense?

**Comment by oliyh** [comment]
Hi @RafaeLeal 

There is an internal representation - you can use it if you are talking to a system that doesn't have a Swagger representation, examples in the tests and in the readme under "No Swagger, no problem":
```
(martian/bootstrap "https://api.org"
                   [{:route-name :load-pet
                     :path-parts ["/pets/" :id]
                     :method :get
                     :path-schema {:id s/Int}}

                    {:route-name :create-pet
                     :produces ["application/xml"]
                     :consumes ["application/xml"]
                     :path-parts ["/pets/"]
                     :method :post
                     :body-schema {:pet {:id   s/Int
                                         :name s/Str}}}])
```

Note that this is used with `bootstrap` as opposed to the Swagger json which is consumed with `bootstrap-swagger`, which first calls `swagger/swagger->handlers` to transform the Swagger json into the internal representation. https://github.com/oliyh/martian/blob/master/core/src/martian/core.cljc#L113

So really what I would expect is needed here would be to enhance the existing `martian.swagger` namespace to be able to deal with v3 as well, and return the same martian representation. I've been meaning to add a spec for the internal data structure to give better error messages but not got around to it.

**Comment by oliyh** [comment]
I have added a spec for the internal handlers in #78 which should help with implementation.
