### ISSUE TITLE
Handling self-sign SSL certificate 

### ISSUE THREAD

**Issue by koprivica** [oliyh/martian#54]
Hi,
this is really great stuff! I really enjoy using martian. But I have issue with self-sign SSL certificate, this is the error I get form repl:

```
SunCertPathBuilderException unable to find valid certification path to requested target  sun.security.provider.certpath.SunCertPathBuilder.build (SunCertPathBuilder.java:141)
```
And this is how my code looks like:

```
(defn authenticate
   "Authenticate"
[x u p]
(let [m (martian-http/bootstrap-swagger x)]
(martian/response-for m :Authenticate {:user u :password p})
))
```

Is there any way i can set program to accept self sign certificates? 

Thanks

**Comment by oliyh** [comment]
Hi,

Which http library are you using? You will need to either write an interceptor to add the appropriate parameters to the request map or to provide them using `:martian.core/request` on each request.

For clj-http it looks like you should be able to use `:key-store` and `:trust-store` and friends.

**Comment by koprivica** [comment]
I am using clj-http as suggested. Is there any way I can skip this verification?

**Comment by oliyh** [comment]
Hi,

You need to set it on the request map that is supplied to clj-http. The following interceptor will do that, you just need to queue it before the http request interceptor.

```clojure
(def go-insecure
  {:name ::perform-request
   :enter (fn [ctx]
                (assoc-in ctx [:request :insecure?] true))})
```

Hope this helps.

By the way this is equivalent to your leave fn looking like this:

```clojure
(fn [{:keys [request] :as ctx}]
            (assoc ctx :response (http/request (assoc request :insecure? true))))
```

**Comment by oliyh** [comment]
Hi @koprivica,
If this was useful, shall I close this issue?
Regards,

**Comment by koprivica** [comment]
Hi @oliyh, 
This was very helpful.
