### ISSUE TITLE
[re-frame] Pass opts parameter to ::request to be consumed by interceptors

### ISSUE THREAD

**Issue by polymeris** [oliyh/martian#56]
I am using JWT-based auth, so I need to set the `Authorization` header of the request based on a token stored in re-frame's database. This can be accomplished easily enough by creating a martian interceptor like this:

``` clojure
(def set-authorization-header
  {:name  ::set-token
   :enter (fn [ctx]
            (if-let [token (:token @re-frame.db/app-db)]
              (assoc-in ctx [:request :headers "Authorization"] (str "Bearer " token))
              ctx))})
```

However, directly accessing the re-frame db atom like that is not very nice, of course. So instead, I suggest extending the `::martian.re-frame/request` event with a fifth argument, which would be a map of options added to the context, i.e.

```clojure
(re-frame/dispatch [::martian.re-frame/request operation-id data on-success on-failure {:authorization-token "foo"}])
```

would result in `ctx` containing a key `:opts` mapping to `{:authorization-token "foo"}`

I am willing to submit a PR if you think this is a good idea.

**Comment by oliyh** [comment]
Hi @polymeris,

How are you bootstrapping Martian, from swagger.json or from your own definition?

Either way, ideally the Authorization header would be declared in the definition and you would populate it by just passing `{:authorization (str "Bearer " token)}` in as a normal parameter.

If it's not declared as part of the route I would still recommend the same approach i.e. keep your interceptor but change it to read the token from the `:params` map in the context, and then pass the token in the normal data argument in `:martian.re-frame/request`.

One other option - if you have the token available when you bootstrap Martian - is to build your interceptor closing over the token, and then include it in the interceptors provided as part of the `init` call.

Hope this helps, let me know if you have any more questions?

**Comment by oliyh** [comment]
Hi @polymeris,
If this was useful, shall I close this issue?
Regards,

**Comment by polymeris** [comment]
Hi,
I haven't had the opportunity to test it, but yes, I think the issue is with my `swagger.json` not specifying security parameters.
I'll close this and reopen if I still have problems.

Thanks a lot.
