### ISSUE TITLE
Support collectionFormat

### ISSUE THREAD

**Issue by pbwolf** [oliyh/martian#61]
For a Swagger parameter specified like this

{"name":"apples",
 "in":"query",
 "type":"array",
 "items":{"type": "string"},
 "collectionFormat":"ssv"}

martian constructs an HTTP request that HttpClient logs like this:
  GET igloo?apples=red&apples=green HTTP/1.1

but the ReST service expects apples=red%20green

collectionFormat is described at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object

**Comment by dummaso** [comment]
Hi!
Any updates on this / any way one can support? Just ran into this issue myself :D

**Comment by oliyh** [comment]
Hello,

No updates on this I'm afraid, I haven't had time to work on it.

**Comment by oliyh** [comment]
I just tried this:
https://github.com/oliyh/martian/compare/master...collection-format-again

But then found I had already had a go at this before!
https://github.com/oliyh/martian/compare/master...collection-format

I think I prefer this new attempt, it's a bit more self-contained.

**Comment by oliyh** [comment]
Deployed in `0.1.27-SNAPSHOT` - please try it and let me know
