### ISSUE TITLE
[Bug] Martian is not respecting Path Item Object's parameters

### ISSUE THREAD

**Issue by RafaeLeal** [oliyh/martian#74]
In the OpenAPI-Specification 2.0 (same as Swagger 2.0) you can nest parameters like this:
```json
{
  "paths": {
    "/api/pets/{id}": {
      "get": {
        "method": "get",
        "parameters": [
          {
            "name": "watch",
            "type": "string",
            "in": "query"
          }
        ]
      },
      "parameters": [
        {
          "name": "id",
          "type": "string",
          "in": "path",
          "required": true
        }
      ]
    }
  }
}

```

But `martian` is only looking into `parameters` inside `get` (or any other http verb)

Reference:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemObject

**Comment by oliyh** [comment]
Hi,

Thank you for this, a very welcome addition.
