### ISSUE TITLE
Update readme to include new link to talk

### ISSUE THREAD

**Issue by bhougland18** [oliyh/martian#79]
Can you update the documentation to provide a new link to your ClojureX Bytes talk (if you have a copy)?  It looks like the Skillsmatter site is no longer :(

https://skillsmatter.com/skillscasts/8843-clojure-bytes#video

**Comment by oliyh** [comment]
I'm afraid I don't have a copy, if anyone knows of somewhere to obtain it I would be grateful! In the meantime the slides are at http://oliyh.github.io/martian/clojurex-bytes/#/

**Comment by bhougland18** [comment]
no problem.  The library looks incredible, thank you!

**Comment by oliyh** [comment]
Looks like it will be restored after all! https://www.skillsmatter.com/

**Comment by oliyh** [comment]
Woohoo it's back online at the original link!
