### ISSUE TITLE
how to add custom cookies using martian and clj-http

### ISSUE THREAD

**Issue by bhougland18** [oliyh/martian#84]
I apologize for submitting an issue for a question, but how would you add a clj-http cookiestore as an interceptor?  I am assuming that is the correct way to accomplish this objective.

To do this using native clj-http one could do:

(def cs (clj-http.cookies/cookie-store))

 (def http-client-response
    (clj-http.client/get
      "https://httpbin.org/cookies"
      {:cookie-store cs})))

**Comment by oliyh** [comment]
Hi @bhougland18 

I would approach it like this:

```clojure
(defn with-cookie-store [cookie-store]
  {:name ::with-cookie-store
   :enter (fn [ctx]
            (assoc-in ctx [:request :cookie-store] cookie-store))})

(defn build-martian []
  (let [cookie-store (clj-http.cookies/cookie-store)]
    (martian.clj-http/bootstrap-swagger "http://swagger.com/swagger.json"
                                        {:interceptors (cons (with-cookie-store cookie-store)
                                                             martian.clj-http/default-interceptors))))
```

The entire map built up under the `:request` key is given to `clj-http.client/request` so by putting your cookie store in there it should work as required.

Hope this helps

**Comment by oliyh** [comment]
Hi @bhougland18 shall I close the issue?

**Comment by bhougland18** [comment]
Oliver,

Yes.  Sorry, I have been very busy.  I am really grateful for your help.

**Comment by oliyh** [comment]
Great, thanks for letting me know.

**Comment by tommy-mor** [comment]
This helped me, thank you for the snippet
