### ISSUE TITLE
Resolve parameter references

### ISSUE THREAD

**Issue by kpmg-jp-jnorton** [oliyh/martian#86]
Based on a cursory review of martian, the resolving of parameter references is not supported.

`$ref: "#/parameters/xyzParam"`

Can you provide some insights on how you would consider to extend the current implementation to add support for this feature?

Thank you.

**Comment by oliyh** [comment]
Hi,

Pretty sure it does support those, the relevant code is here: https://github.com/oliyh/martian/blob/5e763e84c7153bdf486002c5a5563c6dd1154f35/core/src/martian/schema.cljc#L132

It is tested here: https://github.com/oliyh/martian/blob/5e763e84c7153bdf486002c5a5563c6dd1154f35/core/test/martian/schema_test.cljc#L8

Do you have any experience of it not working?
Thanks

**Comment by kpmg-jp-jnorton** [comment]
Yes, I have an experience.

As I understand swagger 2.0 specification and the martian implementation, the code only handles "definitions" references and not "definitions" and "parameters" references.

See here:
https://github.com/oliyh/martian/blob/master/core/src/martian/schema.cljc#L93

**Comment by kpmg-jp-jnorton** [comment]
Here is a document that describes "parameters" references.

https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/v2.0/REUSE.md

```
Local references
When referencing locally (within the current document), the target references should follow the conventions, as defined by the spec:

Parameters -> #/parameters
```

**Comment by kpmg-jp-jnorton** [comment]
I created a tentative pull request for this issue #87.

I briefly tested with a public swagger specification.  If this approach is acceptable, I can try to add a few unit tests.

**Comment by kpmg-jp-jnorton** [comment]
Please review the most recent commit #87.  Thank you.
