### ISSUE TITLE
java 8 build

### ISSUE THREAD

**Issue by patrick-galvin** [oliyh/martian#97]
Any chance we can do a release build with java 8 going forwards? I have done one locally and encountered no issues

thanks for the awesome lib

**Comment by oliyh** [comment]
Hi,

I'm not entirely sure I understand this - the release is built as pure clj/s source files with no AOT. I do this using Java 11 on my local machine. Does this not work on Java 8?

Thanks

**Comment by patrick-galvin** [comment]
Hi Oli,

This was my fault. As part of mucking around with martian I had imported the Martian record!

Sorry for the confusion
