### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by gitsly** [oliyh/martian#98]
Hi, I'm testing this out, new to swagger and new to martian.
I've tested it from clojure with OK results against homemade swagger api (metosin/compojure-api) and the pedestal sample app
with simplest code (taken from README.md) in this repo:

(let [m (martian-http/bootstrap-swagger "http://pedestal-api.herokuapp.com/swagger.json")]
  (martian/explore m))

In clojure this works ok, but when trying out from cljs (with [martian.cljs-http :as martian-http]) the above code always returns => []
I created sample cljs project to test with: lein new figwheel martiantestapp1, added dependencies and above code
Any hints for or gotchas to get the cljs martian working?

**Comment by oliyh** [comment]
Hi,

`martian.cljs-http/bootstrap-swagger` returns a core.async channel that delivers the Martian instance, rather than returning it directly - this is due to the asynchronous nature of web requests in JavaScript.

The following should work (and if it does, let me know - the documentation for this module is rather lacking!):

```clj
(require '[martian.core :as martian])
(require '[martian.cljs-http :as martian-http])
(require '[cljs.core.async :refer [<!]])
(require-macros '[cljs.core.async.macros :refer [go]])

(go 
  (let [m (<! (martian-http/bootstrap-swagger "")]
    (println (martian/explore m))))
```
Hope this helps!

**Comment by oliyh** [comment]
If you happen to use re-frame then the Martian module for that hides the asynchronicity from you:

https://github.com/oliyh/martian/tree/master/re-frame

**Comment by gitsly** [comment]
This works!, thanks for quick and precise reply. 
I haven't used core async enough to spot the obvious...

**Comment by oliyh** [comment]
Glad it worked for you! I've updated the docs.
https://github.com/oliyh/martian/blob/master/cljs-http/README.md
